#include "vt100.h"
#include "StringBuilder.h"

static const char_t ParamSeparator = ';';
#define VT100_Base 10

StringBuilder *ConstructCommand(char *buffer, uint16_t capacity)
{
    StringBuilder *builder = StringBuilder_Construct(buffer, capacity);
    uint8_t err = StringBuilder_AppendString(builder, VT100_CommandStart, 2);
    // if (err != S_OK) return NULL;
    return builder;
}

static const char *ReportDeviceCode_End = "0c";
//#define ReportDeviceCode	"\x1b[{CODE}0c"
// Generated by the device in response to Query Device Code request.
StringBuilder *VT100_ReportDeviceCode(char *buffer, uint16_t capacity, uint8_t code)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, code, VT100_Base);
    err = StringBuilder_AppendString(builder, ReportDeviceCode_End, 2);

    return builder;
}

static const char_t ReportCursorPosition = 'R';
//#define ReportCursorPosition(r, c)	"\x1b[{ROW};{COLUMN}R"
// Generated by the device in response to a Query Cursor Position request; reports current cursor position.
StringBuilder *VT100_ReportCursorPosition(char *buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint16(builder, row, VT100_Base);
    err = StringBuilder_AppendChar(builder, ParamSeparator);
    err = StringBuilder_AppendUint16(builder, col, VT100_Base);
    err = StringBuilder_AppendChar(builder, ReportCursorPosition);

    return builder;
}

static const char_t CursorHome_End = 'H';
//#define CursorHome 		"\x1b[{ROW};{COLUMN}H"
//#define CursorHome 		"\x1b[H"
// Sets the cursor position where subsequent text will begin. If no row/column parameters are provided
// (ie. "\x1b[H), the cursor will move to the home position, at the upper left of the screen.
StringBuilder *VT100_CursorHome_At(char *buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint16(builder, row, VT100_Base);
    err = StringBuilder_AppendChar(builder, ParamSeparator);
    err = StringBuilder_AppendUint16(builder, col, VT100_Base);
    err = StringBuilder_AppendChar(builder, CursorHome_End);

    return builder;
}

static const char_t CursorUp_End = 'A';
//#define CursorUp		"\x1b[{COUNT}A"
#define CursorUp "\x1b[A"
// Moves the cursor up by COUNT rows; the default count is 1.
StringBuilder *VT100_CursorUp_Count(char *buffer, uint16_t capacity, uint8_t count)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, count, VT100_Base);
    err = StringBuilder_AppendChar(builder, CursorUp_End);

    return builder;
}

static const char_t CursorDown_End = 'B';
//#define CursorDown		"\x1b[{COUNT}B"
#define CursorDown "\x1b[B"
// Moves the cursor down by COUNT rows; the default count is 1.
StringBuilder *VT100_CursorDown_Count(char *buffer, uint16_t capacity, uint8_t count)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, count, VT100_Base);
    err = StringBuilder_AppendChar(builder, CursorDown_End);

    return builder;
}

static const char_t CursorForward_End = 'C';
//#define CursorForward		"\x1b[{COUNT}C"
#define CursorForward "\x1b[C"
// Moves the cursor forward by COUNT columns; the default count is 1.
StringBuilder *VT100_CursorForward_Count(char *buffer, uint16_t capacity, uint8_t count)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, count, VT100_Base);
    err = StringBuilder_AppendChar(builder, CursorForward_End);

    return builder;
}

static const char_t CursorBackward_End = 'D';
#define CursorBackward "\x1b[{COUNT}D"
// Moves the cursor backward by COUNT columns; the default count is 1.
StringBuilder *VT100_CursorBackward_Count(char *buffer, uint16_t capacity, uint8_t count)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, count, VT100_Base);
    err = StringBuilder_AppendChar(builder, CursorBackward_End);

    return builder;
}

static const char_t ForceCursorPosition_End = 'f';
//#define ForceCursorPosition	"\x1b[{ROW};{COLUMN}f"
#define ForceCursorPosition "\x1b[f"
// Identical to Cursor Home.
StringBuilder *VT100_ForceCursorPosition_At(char *buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint16(builder, row, VT100_Base);
    err = StringBuilder_AppendChar(builder, ParamSeparator);
    err = StringBuilder_AppendUint16(builder, col, VT100_Base);
    err = StringBuilder_AppendChar(builder, ForceCursorPosition_End);

    return builder;
}

static const char_t ScrollScreen_End = 'r';
//#define ScrollScreen		"\x1b[{start};{end}r"
// Enable scrolling from row {start} to row {end}.
StringBuilder *VT100_ScrollScreen_Range(char *buffer, uint16_t capacity, uint8_t start, uint8_t end)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, start, VT100_Base);
    err = StringBuilder_AppendChar(builder, ParamSeparator);
    err = StringBuilder_AppendUint8(builder, end, VT100_Base);
    err = StringBuilder_AppendChar(builder, ScrollScreen_End);

    return builder;
}

static const char_t SetAttributeMode_End = 'm';
#define SetAttributeMode "\x1b[{attr1};{attr2};{attrn}m"
// Sets multiple display attribute settings. The following lists standard attributes:
StringBuilder *VT100_SetAttributeMode(void *buffer, uint16_t capacity, uint8_t value)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, value, VT100_Base);
    err = StringBuilder_AppendChar(builder, SetAttributeMode_End);

    return builder;
}

StringBuilder *VT100_SetAttributeMode_Begin(void *buffer, uint16_t capacity, uint8_t value)
{
    StringBuilder *builder = ConstructCommand(buffer, capacity);
    uint8_t err = StringBuilder_AppendUint8(builder, value, VT100_Base);

    return builder;
}

result_t VT100_SetAttributeMode_Add(StringBuilder *builder, uint8_t value)
{
    return StringBuilder_AppendUint8(builder, value, VT100_Base);
}

result_t VT100_SetAttributeMode_End(StringBuilder *builder)
{
    return StringBuilder_AppendChar(builder, SetAttributeMode_End);
}
