#include "vt100.h"

const char ParamSeparator = ';'

StringBuilder* ConstructCommand(char* buffer, uint16_t capacity)
{
	StringBuilder* strBuilder = StringBuilder_Construct(buffer, capacity);
	uint8_t err = StringBuilder_AppendString(strBuilder, VT100_CommandStart);
	//if (err != S_OK) return NULL;
	return strBuilder;
}

//#define ReportDeviceCode	"\x1b[{CODE}0c"
// Generated by the device in response to Query Device Code request.
StringBuilder* VT100_ReportDeviceCode(char* buffer, uint16_t capacity, uint8_t code)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, code);
	err = StringBuilder_AppendString(strBuilder, "0c");
	
	return strBuilder;
}


//#define ReportCursorPosition(r, c)	"\x1b[{ROW};{COLUMN}R"
// Generated by the device in response to a Query Cursor Position request; reports current cursor position.
StringBuilder* VT100_ReportCursorPosition(char* buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint16(strBuilder, row);
	err = StringBuilder_AppendChar(strBuilder, ParamSeparator);
	err = StringBuilder_AppendUint16(strBuilder, col);
	err = StringBuilder_AppendChar(strBuilder, 'R');
	
	return strBuilder;
}

//#define CursorHome 		"\x1b[{ROW};{COLUMN}H"
#define CursorHome 		"\x1b[H"
//Sets the cursor position where subsequent text will begin. If no row/column parameters are provided 
// (ie. "\x1b[H), the cursor will move to the home position, at the upper left of the screen.
StringBuilder* VT100_CursorHome(char* buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint16(strBuilder, row);
	err = StringBuilder_AppendChar(strBuilder, ParamSeparator);
	err = StringBuilder_AppendUint16(strBuilder, col);
	err = StringBuilder_AppendChar(strBuilder, 'H');
	
	return strBuilder;
}

//#define CursorUp		"\x1b[{COUNT}A"
#define CursorUp		"\x1b[A"
// Moves the cursor up by COUNT rows; the default count is 1.
StringBuilder* VT100_CursorUp(char* buffer, uint16_t capacity, uint8_t count)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, count);
	err = StringBuilder_AppendChar(strBuilder, 'A');
	
	return strBuilder;
}


//#define CursorDown		"\x1b[{COUNT}B"
#define CursorDown		"\x1b[B"
// Moves the cursor down by COUNT rows; the default count is 1.
StringBuilder* VT100_CursorDown(char* buffer, uint16_t capacity, uint8_t count)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, count);
	err = StringBuilder_AppendChar(strBuilder, 'B');
	
	return strBuilder;
}

//#define CursorForward		"\x1b[{COUNT}C"
#define CursorForward		"\x1b[C"
// Moves the cursor forward by COUNT columns; the default count is 1.
StringBuilder* VT100_CursorForward(char* buffer, uint16_t capacity, uint8_t count)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, count);
	err = StringBuilder_AppendChar(strBuilder, 'C');
	
	return strBuilder;
}

#define CursorBackward		"\x1b[{COUNT}D"
// Moves the cursor backward by COUNT columns; the default count is 1.
StringBuilder* VT100_CursorDown(char* buffer, uint16_t capacity, uint8_t count)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, count);
	err = StringBuilder_AppendChar(strBuilder, 'D');
	
	return strBuilder;
}

//#define ForceCursorPosition	"\x1b[{ROW};{COLUMN}f"
#define ForceCursorPosition	"\x1b[f"
// Identical to Cursor Home.
StringBuilder* VT100_ForceCursorPosition(char* buffer, uint16_t capacity, uint16_t row, uint16_t col)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint16(strBuilder, row);
	err = StringBuilder_AppendChar(strBuilder, ParamSeparator);
	err = StringBuilder_AppendUint16(strBuilder, col);
	err = StringBuilder_AppendChar(strBuilder, 'f');
	
	return strBuilder;
}

//#define ScrollScreen		"\x1b[{start};{end}r"
// Enable scrolling from row {start} to row {end}.
StringBuilder* VT100_ScrollScreen(char* buffer, uint16_t capacity, uint8_t start, uint8_t end)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, start);
	err = StringBuilder_AppendChar(strBuilder, ParamSeparator);
	err = StringBuilder_AppendUint8(strBuilder, end);
	err = StringBuilder_AppendChar(strBuilder, 'r');
	
	return strBuilder;
}

#define SetAttributeMode	"\x1b[{attr1};{attr2};{attrn}m"
// Sets multiple display attribute settings. The following lists standard attributes:
StringBuilder* VT100_SetAttributeMode(void* buffer, uint16_t capacity, uint8_t value)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, value);
	err = StringBuilder_AppendChar(strBuilder, 'm');
	
	return strBuilder;
}

StringBuilder* VT100_Begin_SetAttributeMode(void* buffer, uint16_t capacity, uint8_t value)
{
	StringBuilder* strBuilder = ConstructCommand(buffer, capacity);
	uint8_t err = StringBuilder_AppendUint8(strBuilder, value);
	
	return strBuilder;
}

result_t VT100_Add_SetAttributeMode(StringBuilder* buffer, uint8_t value)
{
	return StringBuilder_AppendUint8(strBuilder, value);
}

result_t VT100_End_SetAttributeMode(StringBuilder* buffer)
{
	return StringBuilder_AppendChar(strBuilder, 'm');
}
